language: python

# use the faster container-based architecture
sudo: false

addons:
  apt_packages:
    - pandoc

# versions to test
# list of packages in miniconda:
# http://repo.continuum.io/pkgs/free/linux-64/index.html
matrix:
  include:
    - python: 3.6
      env:
        - PYTHONVERSION==3.6
        - NUMPYVERSION=
        - SCIPYVERSION=
        - MATPLOTLIBVERSION=
    - python: 3.7
      env:
        - PYTHONVERSION==3.5
        - NUMPYVERSION=
        - SCIPYVERSION=
        - MATPLOTLIBVERSION=
    - python: 3.8
      env:
        - PYTHONVERSION==3.5
        - NUMPYVERSION=
        - SCIPYVERSION=
        - MATPLOTLIBVERSION=

# install Miniconda; use it to install dependencies
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $(pwd)/miniconda
  - export PATH="$(pwd)/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - DEPS="pip nose coverage"
  - conda create -q -n test-environment python$PYTHONVERSION $DEPS
  - conda install -n test-environment --yes numpy$NUMPYVERSION
  - conda install -n test-environment --yes scipy$SCIPYVERSION
  - conda install -n test-environment --yes matplotlib$MATPLOTLIBVERSION
  - conda install -n test-environment --yes h5py
  - source activate test-environment
  - pip install coveralls
  - pip install ipython
  - pip install -e .[dev,doc]
  - pip freeze


# Select a proper matplotlib backend
before_script:
  - mkdir -p ~/.config/matplotlib
  - "echo backend : Agg > ~/.config/matplotlib/matplotlibrc"

# Run unit tests for the code, docstrings and documentation
script:
  - travis_wait 30 python -m nose -c setup.cfg
  - cd doc
  - travis_wait 50 make doctest
  - cd ..

# Run doctests only for recent enough NumPy.
# - python -c "import sys; import numpy; from distutils.version import StrictVersion; sys.exit(StrictVersion(numpy.__version__) < StrictVersion('1.11'))"
# - if [ $? -eq 0]; then travis_wait 50 make doctest; fi

# if tests fail, upload images to imgur
after_failure:
  - wget http://imgur.com/tools/imgurbash.sh
  - for img in result_images/test_plot/*.png; do echo -e "\n$img"; bash imgurbash.sh $img; done

# check coverage
after_script:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d33dd85624e42382050a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
